os: unstable
cache:
  - node_modules
  - '%LocalAppData%\electron-builder\cache'
  - '%LocalAppData%\electron\Cache'

environment:
  matrix:
    - nodejs_version: 8

install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm install -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm set progress=false
  - npm install

matrix:
  fast_finish: true

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

test_script:
  - npm run ng lint
  - npm run test
  - npm run electron:windows
